resume:
    dir:

data:
    type: edit3d.multimodal
    cate_id: "02691156" 
    sketch_name: "sketch-T-2.png"
    split_files:
        train: ./datasets/splits/sv2_planes_train.json
        test: ./datasets/splits/sv2_planes_test.json
    sdf_data_dir:
        surface: ./datasets/sdf/03001627_surface
        sphere: ./datasets/sdf/03001627_sphere
        sketch: ./datasets/sdf/03001627_sketch
        color: ./datasets/sdf/03001627_color
    train:
        num_sample_points:
            fine: 2048
            coarse: 1024
        num_repeats: 1
        batch_size: 32
        num_workers: 4
        imsize: 128
    test:
        test_on_train_set: False
        num_sample_points:
            fine: 2048
            coarse: 1024
        num_repeats: 100
        batch_size: 32
        subset: 32
        num_workers: 4
        imsize: 128  

trainer:
    type: edit3d.trainers.trainer_multimodal

    latent_dim: 128

    latent_code_shape:
        dim: 128
        type: VADLogVar
        mu_init_std: # default: 1.0 / np.sqrt(self.dim)
        logvar_init_std: 
        logvar_init_mean: 0.0
        fix_var: False
        augment_latent: True
        sample_twice: True

    latent_code_color:
        dim: 128
        type: VADLogVar
        mu_init_std: # default: 1.0 / np.sqrt(self.dim)
        logvar_init_std: 
        logvar_init_mean: 0.0
        fix_var: False
        augment_latent: True
        sample_twice: True


    detach_latent_coarse: True # useless 
    detach_latent_fine: False # useless
    kld_weight_shape: 1.e-5
    kld_weight_color: 1.e-5
    attr_reg_weight: 0.001 # useless
    color_shape_joint: True # backprop grad from color3d to sdf

    optim_primitive:
        type: Adam
        lr: 5.e-4
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-4
            interval: 700 # epochs
            factor: 0.5

    optim_deepsdf:
        type: Adam
        lr: 5.e-4
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-4
            interval: 700
            factor: 0.5

    optim_colorsdf:
        type: Adam
        lr: 5.e-4
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-4
            interval: 700
            factor: 0.5

    optim_imgen:
        type: Adam
        lr: 5.e-4
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-4
            interval: 700
            factor: 0.5

    optim_latentcode:
        type: Adam
        lr: 5.e-1
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-1
            interval: 700
            factor: 0.5

    loss_fine_shape:
        type: clamped_l1_correct
        trunc: 0.1
        weight: 1.0
    loss_coarse_shape:
        type: onesided_l2
        weight: 1.0
    loss_image: # sketch
        type: binary_cross_entropy
        weight: 1.0
    loss_color2D: # l1 for color 
        type: l1
        weight: 1.0
    loss_color3D: # l1 for color 
        type: l1
        weight: 0.1

    mixture_loss: True # use proper mixture-of-experts loss instead of approximaton
    epochs: 200
    
viz:
  log_interval: 1
  save_interval: 20
  
render:
    cam_model: 'Orthographic' # Perspective
    #cam_model: 'Perspective'
    bsphere_r: 1.1
    ver_scale: 2.15
    rot_hor_deg: 60
    rot_ver_deg: -28.647889
    sdf_iso_level: 0.001
    sdf_clamp: 0.05
    sdf_gain: 1
    numerical_normal: False
    resolution: [480, 480]
    steps: 96
    fg_color: [0.99609375, 0.89453125, 0.796875] # [255 / 256, 229 / 256, 204 / 256]
    bg_color: [1.0, 1.0, 1.0]
    selected_color: [0.0, 0.5843, 1.0]

render_web:
    cam_model: 'Orthographic'
    bsphere_r: 1.1
    ver_scale: 2.15
    rot_hor_deg: 60
    rot_ver_deg: -28.647889
    sdf_iso_level: 0.001
    #sdf_clamp: 0.05
    sdf_clamp: 0.08
    sdf_gain: 1
    numerical_normal: False
    resolution: [200, 200] # Lower resolution for web demo
    steps: 64
    fg_color: [0.99609375, 0.89453125, 0.796875] # [255 / 256, 229 / 256, 204 / 256]
    bg_color: [1.0, 1.0, 1.0]
    selected_color: [0.0, 0.5843, 1.0]
    
manip:
    latent:
        type: VADLogVar
        mu_init_std: # default: 1.0 / np.sqrt(self.dim)
        logvar_init_std: 
        logvar_init_mean: 0.0
        fix_var: False
        augment_latent: False
        sample_twice: False
    optim:
        type: Adam
        lr: 1.e-1 # for VAD_logvar, one step per epoch
        betas: [0.9, 0.999]
        eps: 1.e-8
        weight_decay: 0
        
val:
    latent_code:
        type: VADLogVar
        mu_init_std: # default: 1.0 / np.sqrt(self.dim) 
        logvar_init_std: 
        logvar_init_mean: 0.0
        fix_var: False
        augment_latent: True
        sample_twice: True
    optim_latentcode:
        type: Adam
        lr: 5.e-1 # for AE
        eps: 1.e-8
        weight_decay: 0
        lr_scheduler:
            type: Step
            initial: 5.e-1
            interval: 2
            factor: 0.5
    epochs: 8

models:
    deepsdf:
        type: models.deepsdf_mlp9_feat
        dropout: True
        dropout_prob: 0.2
        use_tanh: True
        in_ch: 131 # 128 + 3
        out_ch: 1
        hidden_ch: 512
        feat_layer: 2

    colorsdf:
        type: models.colorsdf_mlp9
        use_tanh: True
        hidden_ch: 512
        color_in_ch: 643 # 128 + 3 + 512
        out_ch: 3

    im_gen: # sketch
        type: models.image_cnn
        in_ch: 128
        out_ch: 16384 # 128 * 128
        hidden_ch: 512
        RGB: False

    color_gen: # color image
        type: models.image_cnn_color
        in_ch:  256 # 128 + 128
        out_ch: 16384 # 128 * 128
        hidden_ch: 512
        RGB: True

    prim_attr:
        type: models.deepsdf_mlp9
        dropout: False
        dropout_prob:
        use_tanh: False
        in_ch: 128
        out_ch: 1024 # 4 * 256
        hidden_ch: 512

    prim_sdf:
        type: models.sdfsphere
        smooth: True
        smooth_factor: 100
        return_idx: False

